export const galleryData = {
  title: "Aesthetic Delights at Dolci",
  subtitle: "A Gallery of Culinary Artistry",
  images: [
    {
      id: "1",
      url: "https://res.cloudinary.com/dq7bzydqz/image/upload/v1758764551/Dolci_Square_Web-Images_0025_Peach-_-Berry-Pocket-Square-_wo-fork_y9nvpt.webp",
      alt: "Tiramisu Croissant",
      category: "viennoiserie",
    },
    {
      id: "2",
      url: "https://res.cloudinary.com/dq7bzydqz/image/upload/v1758764550/Dolci_Square_Web-Images_0024_Peach-_-Berry-Pocket-Square-_wo-fork_mnddvc.webp",
      alt: "French Classic Croissant",
      category: "viennoiserie",
    },
    {
      id: "3",
      url: "https://res.cloudinary.com/dq7bzydqz/image/upload/v1758764549/Dolci_Square_Web-Images_0023_Peach-_-Berry-Pocket-Square-_wo-fork_xbakyu.webp",
      alt: "Peach & Berry Pocket",
      category: "viennoiserie",
    },
    {
      id: "4",
      url: "https://res.cloudinary.com/dq7bzydqz/image/upload/v1758764548/Dolci_Square_Web-Images_0021_Pain-Au-Chocolat-Square_kbairc.webp",
      alt: "Pain Au Chocolat",
      category: "viennoiserie",
    },
    {
      id: "5",
      url: "https://res.cloudinary.com/dq7bzydqz/image/upload/v1758764547/Dolci_Square_Web-Images_0020_Raspberry-Cruffin-Square_wdwg2o.webp",
      alt: "Raspberry Cruffin",
      category: "viennoiserie",
    },
    {
      id: "6",
      url: "https://res.cloudinary.com/dq7bzydqz/image/upload/v1758764524/Dolci_Square_Web-Images_0019_Sticky-Walnut-Cake-Square_eyrj7b.webp",
      alt: "Sticky Walnut Cake",
      category: "pastries",
    },
    {
      id: "7",
      url: "https://res.cloudinary.com/dq7bzydqz/image/upload/v1758764524/Dolci_Square_Web-Images_0018_Triple-Chocolate-Cake-Square_bt4lbv.webp",
      alt: "Triple Chocolate Cake",
      category: "pastries",
    },
    {
      id: "8",
      url: "https://res.cloudinary.com/dq7bzydqz/image/upload/v1758764524/Dolci_Square_Web-Images_0017_Dolci_s-Signature-Tiramisu-Square_1_ryxknl.webp",
      alt: "Dolci's Signature Tiramisu",
      category: "pastries",
    },
    {
      id: "9",
      url: "https://res.cloudinary.com/dq7bzydqz/image/upload/v1758764524/Dolci_Square_Web-Images_0016_Matcha-Mascarpone-Cake-Square_hbqc5n.webp",
      alt: "Matcha Mascarpone Cake",
      category: "pastries",
    },
    {
      id: "10",
      url: "https://res.cloudinary.com/dq7bzydqz/image/upload/v1758764524/Dolci_Square_Web-Images_0009_Basque-Cheese-Cake-Square_e62vtw.webp",
      alt: "Basque Cheese Cake",
      category: "pastries",
    },
    {
      id: "11",
      url: "https://res.cloudinary.com/dq7bzydqz/image/upload/v1759342676/Oreo_Cheese_Cake_Square_2_oxodrv.webp",
      alt: "Oreo Cheese Cake",
      category: "pastries",
    },
    {
      id: "12",
      url: "https://res.cloudinary.com/dq7bzydqz/image/upload/v1759342676/Biscoff_Cheese_Cake_Square_2_vvbql7.webp",
      alt: "Biscoff Cheese Cake",
      category: "pastries",
    },
    {
      id: "13",
      url: "https://res.cloudinary.com/dq7bzydqz/image/upload/v1758764536/Dolci_Square_Web-Images_0002_Cappuccino-Square_fgr6qb.webp",
      alt: "Cappuccino",
      category: "beverages",
    },
    {
      id: "14",
      url: "https://res.cloudinary.com/dq7bzydqz/image/upload/v1758764535/Dolci_Square_Web-Images_0001_Caffe-Latte-square_rpomhy.webp",
      alt: "Caffe Latte",
      category: "beverages",
    },
    {
      id: "15",
      url: "https://res.cloudinary.com/dq7bzydqz/image/upload/v1758764537/Hot_Chocolate_Square_alv4zz.webp",
      alt: "Hot Chocolate",
      category: "beverages",
    },
    {
      id: "16",
      url: "https://res.cloudinary.com/dq7bzydqz/image/upload/v1758764535/Dolci_Square_Web-Images_0000_Cafe-Mocha-Square_vbqpfu.webp",
      alt: "Caffe Mocha",
      category: "beverages",
    },
    {
      id: "17",
      url: "https://res.cloudinary.com/dq7bzydqz/image/upload/v1758764537/Classic_Cold_Brew_Square_qqrzwv.webp",
      alt: "Classic Cold Brew",
      category: "beverages",
    },
    {
      id: "18",
      url: "https://res.cloudinary.com/dq7bzydqz/image/upload/v1758764538/Iced_Americano_Square_rzhld2.webp",
      alt: "Iced Americano",
      category: "beverages",
    },
    {
      id: "19",
      url: "https://res.cloudinary.com/dq7bzydqz/image/upload/v1758764540/Vietnamese_Cold_Coffee_Sqauare_fkboyz.webp",
      alt: "Vietnamese Cold Coffee",
      category: "beverages",
    },
    {
      id: "20",
      url: "https://res.cloudinary.com/dq7bzydqz/image/upload/v1758764539/Orange_Cold_Brew_Square_degucl.webp",
      alt: "Orange Cold Brew",
      category: "beverages",
    },
    {
      id: "21",
      url: "https://res.cloudinary.com/dq7bzydqz/image/upload/v1758764538/Dolci_Square_Web-Images_0002_Popcorn_Latte-Square_cyky7f.webp",
      alt: "Popcorn Latte",
      category: "beverages",
    },
    {
      id: "22",
      url: "https://res.cloudinary.com/dq7bzydqz/image/upload/v1758764534/Dolci_Square_Web-Images_0005_Protein-Power-House-Burger-Square_ioqh9o.webp",
      alt: "Dolci Club Egg Sandwich",
      category: "food",
    },
    {
      id: "23",
      url: "https://res.cloudinary.com/dq7bzydqz/image/upload/v1758764534/Dolci_Square_Web-Images_0004_Protein-Power-House-Burger-Square_hkldkj.webp",
      alt: "Cheesy Corn, Spinach & Jalapeno Sandwich",
      category: "food",
    },
    {
      id: "24",
      url: "https://res.cloudinary.com/dq7bzydqz/image/upload/v1758764533/Dolci_Square_Web-Images_0003_Protein-Power-House-Burger-Squaren_t69a72.webp",
      alt: "Protein Power House burger",
      category: "food",
    },
    {
      id: "25",
      url: "https://res.cloudinary.com/dq7bzydqz/image/upload/v1758764543/Pesto_Pasta_Square_fgm66b.webp",
      alt: "Pesto Penne Alla Genovese",
      category: "food",
    },
    {
      id: "26",
      url: "https://res.cloudinary.com/dq7bzydqz/image/upload/v1758764541/Arrabiatta_Square_brheu0.webp",
      alt: "Arrabiatta",
      category: "food",
    },
    {
      id: "27",
      url: "https://res.cloudinary.com/dq7bzydqz/image/upload/v1758764541/Creamy_Alfredo_Square_smlfnu.webp",
      alt: "Creamy Alfredo",
      category: "food",
    },
    {
      id: "28",
      url: "https://res.cloudinary.com/dq7bzydqz/image/upload/v1758764540/Aglio_e_olio_Pasta_Square_nvst9l.webp",
      alt: "Aglio e olio",
      category: "food",
    },

    {
      id: "28",
      url: "https://res.cloudinary.com/dq7bzydqz/image/upload/v1761885767/DSC05871_nviao4.webp",
      alt: "",
      category: "ambience",
    },
    {
      id: "31",
      url: "https://res.cloudinary.com/dq7bzydqz/image/upload/v1761885221/xqzkh2kfp7v2xsxddhbs_pnjqaa.webp",
      alt: "",
      category: "ambience",
    },
    {
      id: "29",
      url: "https://res.cloudinary.com/dq7bzydqz/image/upload/v1761885766/DSC05883_uah4qj.webp",
      alt: "",
      category: "ambience",
    },
    {
      id: "30",
      url: "https://res.cloudinary.com/dq7bzydqz/image/upload/v1761885766/DSC05859_fmlq1y.webp",
      alt: "",
      category: "ambience",
    },
    {
      id: "33",
      url: "https://res.cloudinary.com/dq7bzydqz/image/upload/v1761716397/Lavelle_Road_rtkrht.webp",
      alt: "",
      category: "ambience",
    },

    {
      id: "32",
      url: "https://res.cloudinary.com/dq7bzydqz/image/upload/v1761885220/dtr0k3x7enij4vdv6p9q_vjzzez.webp",
      alt: "",
      category: "ambience",
    },
    {
      id: "35",
      url: "https://res.cloudinary.com/dq7bzydqz/image/upload/v1762239921/DSC06492_1_ilg29g.webp",
      alt: "",
      category: "ambience",
    },

    {
      id: "34",
      url: "https://res.cloudinary.com/dq7bzydqz/image/upload/v1762333589/WhatsApp_Image_2025-11-05_at_10.07.35_AM_1_1_uimwuk.webp",
      alt: "",
      category: "ambience",
    },

    {
      id: "35",
      url: "https://res.cloudinary.com/dq7bzydqz/image/upload/v1762239921/DSC06583_cnwm5r.webp",
      alt: "",
      category: "ambience",
    },
  ],
};
